---
title: "test for propensity"
output: html_document
date: "2023-09-08"
---

```{r}
setwd("~/OutSpillover")

source("utils/weight_matrix.R")
source("utils/integrand.R")
source("utils/utils.R")
source("utils/mixed_effects.R")

source("point_estimates/point_estimates.R")
source("variances/bootstrap_variance.R")
source("variances/regression_variance.R")
source("variances/regression_utils.R")
source("variances/regression_utils_neigh.R")

source("propensity/propensity.R")
source("propensity/point_estimate_propensity.R")
source("propensity/propensity_utils.R")
source("propensity/propensity_effect_calc.R")
source("point_estimates/point_estimates_utils.R")
source("propensity/second_stage_utils.R")

source("propensity/propensity_weighted_regression.R")

library(igraph)
library(lme4)
library(boot)
```

```{r}
graph = make_empty_graph(n = 0, directed = FALSE)
  noc = 100
  ss = 100
  
  repeat{
    g2 = sample_gnp(ss, 0.5, directed = FALSE, loops = FALSE)
    graph = disjoint_union(graph, g2)
    if (clusters(graph)$no == noc){
      break}
  }
  G = rep(1:noc, each = ss)
  
  numerator_alpha = 0.5
  denominator_alphas = c(0.4,0.6)
  P = c(0.5,0.5) 
  # Assume random effect ~ N(0, 0.2^2) for each group
  ranef <- rnorm(noc, mean = 0, sd = 0.2)
  group_ef <- rep(ranef, each = ss)
  
  # assign to group 1 (0.4) and group 2 (0.6) randomly
  G1 = sample(c(1,2), length(unique(G)), replace = TRUE, prob = P)
  G1_alpha = denominator_alphas[G1]
  P1 = sapply(G, function(x) G1_alpha[x])
  
  # for each group with assigned treatment probability, the probability of treatment 
  P2 = rep(NA, length(P1))
  A = rep(NA, length(P1))
  # Assume there are 2 covariates
  X1 <- sample(c("M", "F"), size = length(A), replace = TRUE) # M is 1, F is 0
  X1_num <- ifelse(X1 == "M", 1, 0)
  X2 <- rnorm(length(A), mean = 0.5, sd = 1)
  X <- cbind(X1, X2)
  X_type <- c("C", "N")
  
  # A ～ X1 + X2 + P_2[i] + intercept
  
  for (i in 1:length(P1)) {
    # Base denominator assigned to each group
    if(P1[i] == 0.4){
      # mean of X1_num, X2, group_ef = .5, .5, 0
      # intercept = logit(0.4) - 1
      P2[i] = inv.logit(X1_num[i] + X2[i] + group_ef[i] - 1.4 - max(ranef[G1 == 1]))
    }else{
      P2[i] = inv.logit(X1_num[i] + X2[i] + group_ef[i] - 0.6 - max(ranef[G1 == 2]))
    }
  }
  
  df <- as.data.frame((cbind(G, P2)))
  
  for (i in 1:dim(df)[1]) {
    df$A[i] <- sample(c(1, 0), size = 1, prob = c(P2[i], 1-P2[i]))
  }
  A <- df$A
  
  x0 <- as.matrix(c("M", 0.1))
  x1 <- x0
  x1_num <- c(0.1)
  
  X_num <- apply(as.matrix(X[, X_type == "N"]), 2, as.numeric)
  X_cat <- as.matrix(X[, X_type == "C"])
  
  df$treated_neigh <- h_neighsum(graph, df$A, 1) 
  df$interaction1 <- ifelse(X_cat[,1] == "M", 1, 0)  * df$treated_neigh
  df$interaction2 <- X_num[,1] * df$treated_neigh
  
  ##########
  # 2. Outcome model
  aa = 2; bb = 5; cc = 7; dd = 9
  Y = apply(cbind(df$A, df$treated_neigh, df$interaction1, df$interaction2), 1, function(x)  rnorm(1, mean = aa*x[1] + bb*x[2] + cc*x[3] + dd*x[4], sd = 1))  
  H = h_neighborhood(graph, Y, 1) 
  H_M =  h_neighborhood(graph, Y, 1, X_cat, c("M")) 
  df$Y = Y
  df$H = H
  df$H_M = H_M
  
  # 2.1 neighinfo
  neighX = h_neighcov(graph, 1, X, X_type, x1) # average of X for unit j's 1-order neighbor
  neighinfo = list(neighX)
  names(neighinfo) <- c('neighX')
  
  df$X1_num <- X1_num
  df$X2 <- X2
  formula <- H | A  ~  X1_num + X2 + (1|G) | G
  df1 <- df[P1 == 0.4,]
  df2 <- df[P1 == 0.6,]
  
  X <- cbind(1, X1_num, X2)
  allocations = list(c(numerator_alpha, denominator_alphas))
  first_assignments = G1 - 1
  
  cond_X <- cbind(X1, X2)
  propensity_X = X
```

# test for the case with one stage with the package
```{r}
parameters = unlist(propensity_parameter(formula, df)[1])

# the second stage estimator
ipw_propensity_variance_second(parameters = parameters,
                                   allocations = allocations,
                                   causal_estimation_options = 
                                     list(variance_estimation = 'robust'),
                                   integrate_allocation = FALSE,
                                   H = H, propensity_X = X, P = 1,
                                   A = A, G = G, first_assignments = rep(0, noc),
                                   effect_type = "contrast")

# the second stage estimator
ipw_propensity_variance_second(parameters = c(parameters, parameters),
                                   allocations = allocations,
                                   causal_estimation_options = 
                                     list(variance_estimation = 'robust'),
                                   integrate_allocation = FALSE,
                                   H = H, propensity_X = X, P = P,
                                   A = A, G = G, first_assignments = first_assignments,
                                   effect_type = "contrast")

```
0.1208455	0.1382552	# 1
0.1208455 0.1345894 # 0.1, 0.9
0.1208455   0.13669 # 0.3, 0.7
0.1208455	0.1416431	# 0.5, 0.5
0.1208455 0.1491649 # 0.7, 0.3
```{r}
# the only one stage estimator 
ipw_propensity_variance(parameters = parameters,
                        allocations = allocations,
                        causal_estimation_options = 
                          list(variance_estimation = 'robust'),
                        integrate_allocation = FALSE,
                        H = H, X = X,
                        A = A, G = G, effect_type = "contrast")

inferference::interference(formula, allocations = c(0.5, 0.5),
data = df, propensity_integrand = "logit_integrand", causal_estimation_options = 
                          list(variance_estimation = 'robust'))

```

```{r}
parameters1 <- unlist(propensity_parameter(formula, df1)[1])
parameters2 <- unlist(propensity_parameter(formula, df2)[1])
parameters0 = c(parameters1, parameters2)
```

```{r}
ipw_propensity_variance_regression(parameters = parameters0,
                                   allocations = allocations,
                                   causal_estimation_options = 
                                     list(variance_estimation = 'robust'),
                                   integrate_allocation = FALSE,
                                   propensity_X = X,
                                   H = H, P = P,
                                   A = A, G = G, 
                                   first_assignments = first_assignments,
                                   effect_type = "contrast", 
                                   X = cond_X,
                                   x0 = x0, 
                                   X_type = c("C", "N"),
                                   Con_type = "group")
```

```{r}
setwd("~/OutSpillover")
source("propensity/propensity_weighted_regression_diffeqs.R")

ipw_propensity_variance_regression2(parameters = parameters0,
                                            allocations = allocations,
                                            causal_estimation_options =
                                              list(variance_estimation = 'robust'),
                                            integrate_allocation = FALSE,
                                            propensity_X = X,
                                            H = H, P = P,
                                            A = A, G = G,
                                            first_assignments = first_assignments,
                                            effect_type = "contrast",
                                            X = cond_X,
                                            x0 = x0,
                                            X_type = X_type,
                                            Con_type = "group")


```



```{r}
log_likelihood_second <- function(parameters,
                                  integrand,
                                  P, 
                                  first_assignment,
                                  # default is alpha_0 (first stage assignment)
                                  ...)
{
  ## Necessary pieces ##
  integrand <- match.fun(integrand)
  dots      <- list(...)
  dot.names <- names(dots)
  
  ## Integrate() arguments ##
  if(!'lower' %in% dot.names){
    dots$lower <- -Inf
  }
  
  if(!'upper' %in% dot.names){
    dots$upper <- Inf
  }
  
  int.args <- append(get_args(stats::integrate, dots),
                     get_args(integrand, dots))

  ## Calculation ##
  if (length(parameters)%%length(P) != 0) {stop("in log_likelihood_second,
                                                length of parameters and first stage probability is not compatible")}
  if (length(P) == 1 && first_assignment > 0) {stop("in log_likelihood_second,
                                                         first_assignments should be 0 if P = 1")}
  pp <- length(parameters)/length(P)

  args <- append(int.args, list(f = integrand, parameters = 
                                  parameters[(1+pp*(first_assignment)):(pp*(first_assignment+1))]))
  attempt <- try(do.call(stats::integrate, args = args))
  val <- if(is(attempt, 'try-error')) NA else attempt$value
  likelihood = val
  
  return(log(likelihood))
}

```

```{r}
score_calc_deriv <- function(parameters,
                              integrand,
                              P, 
                              first_assignment, 
                              hide.errors = TRUE,
                              propensity_X,
                              ...)
{
  ## Necessary bits ##
  integrand <- match.fun(integrand)
  dots <- list(...)
  
  ## Function arguments ##
  int.args <- append(get_args(integrand, dots),
                     get_args(stats::integrate, dots))
  fargs    <- append(int.args, get_args(numDeriv::grad, dots))
  
  args     <- append(fargs,
                     list(func = log_likelihood_second,
                          x    = parameters,
                          integrand = integrand,
                          first_assignment = first_assignment,
                          P = P,
                          propensity_X = propensity_X))
  
  ## Compute the derivative of the log likelihood for each parameter ##
  do.call(numDeriv::hessian, args = args)
}  


score_matrix_deriv <- function(integrand,
                                A, G, P,
                                parameters,
                                propensity_X,
                                first_assignments,
                                runSilent = TRUE, 
                                ...)
{
  ## Necessary bits ##
  integrand <- match.fun(integrand)
  dots <- list(...)
  XX <- cbind(propensity_X, A, first_assignments[G])
  pp <- ncol(propensity_X)
  gg <- sort(unique(G))
  
  ## Compute score for each group and parameter ##
  int.args <- append(get_args(integrand, dots),
                     get_args(stats::integrate, dots))
  fargs <- append(int.args, get_args(numDeriv::grad, dots))
  
  if(!runSilent) print("Calculating matrix of scores...")
  
  s.list <- by(XX, INDICES = G, simplify = TRUE, 
               FUN = function(xx) {
                 args <- append(fargs, 
                                list(integrand  = integrand, 
                                     parameters = parameters,
                                     A = xx[ , (pp + 1)],
                                     propensity_X = xx[ , 1:pp],
                                     P = P,
                                     first_assignment = xx[, (pp + 2)][1])) 
                 # first assignment for each group is the same, so [1]
                 do.call(score_calc_deriv, args = args)
               })
  
  ## Reshape list into matrix ##
  U11 = matrix(0, nrow = length(parameters), ncol = length(parameters))
  
  for (i in 1:length(gg)) {
    # this is where -1 * U11 comes 
    U11 =  U11 - s.list[[i]]
    #U11 = U11 - s.list[[i]]/sum(first_assignments == first_assignments[i])
  }
  U11 = U11/length(gg)
  U11
}

```

```{r}
score_args <- list(integrand = logit_integrand_second,
                                     propensity_X = X, G = G, P = P,
                                     A = A, # Use B for treatment in scores
                                     parameters = parameters0,
                                     first_assignments = first_assignments,
                                     runSilent  = TRUE)
do.call(score_matrix_deriv, args = score_args)

score_calc_deriv(integrand = logit_integrand_second,
                 A = A[1:50], P = P,
                 parameters = parameters0, propensity_X = X[1:50,],
                 first_assignment = 1)
```

```{r}

```





```{r}
log_likelihood_second <- function(parameters,
                                  integrand,
                                  P, 
                                  first_assignment,
                                  # default is alpha_0 (first stage assignment)
                                  ...)
{
  ## Necessary pieces ##
  integrand <- match.fun(integrand)
  dots      <- list(...)
  dot.names <- names(dots)
  
  ## Integrate() arguments ##
  if(!'lower' %in% dot.names){
    dots$lower <- -Inf
  }
  
  if(!'upper' %in% dot.names){
    dots$upper <- Inf
  }
  
  int.args <- append(get_args(stats::integrate, dots),
                     get_args(integrand, dots))

  ## Calculation ##
  if (length(parameters)%%length(P) != 0) {stop("in log_likelihood_second,
                                                length of parameters and first stage probability is not compatible")}
  if (length(P) == 1 && first_assignment > 0) {stop("in log_likelihood_second,
                                                         first_assignments should be 0 if P = 1")}
  pp <- length(parameters)/length(P)

  args <- append(int.args, list(f = integrand, parameters = 
                                  parameters[(1+pp*(first_assignment)):(pp*(first_assignment+1))]))
  attempt <- try(do.call(stats::integrate, args = args))
  val <- if(is(attempt, 'try-error')) NA else attempt$value
  likelihood = val
  
  return(log(likelihood))
}
```

```{r}
# new estmating eqs
integrand = logit_integrand

score_calc_deriv2 <- function(parameters,
                              integrand,
                              propensity_X,
                              A,
                              hide.errors = TRUE,
                              ...)
{
  ## Necessary bits ##
  integrand <- match.fun(integrand)
  dots <- list(...)
  
  ## Function arguments ##
  int.args <- append(get_args(integrand, dots),
                     get_args(stats::integrate, dots))
  fargs    <- append(int.args, get_args(numDeriv::grad, dots))
  
  args     <- append(fargs,
                     list(func = log_likelihood,
                          x    = parameters,
                          integrand = integrand,
                          X = propensity_X,
                          A = A))
  
  ## Compute the derivative of the log likelihood for each parameter ##
  do.call(numDeriv::hessian, args = args)
} 
```

```{r}
score_calc_deriv2(integrand = logit_integrand,
                 parameters = parameters1,
                 propensity_X = X[1:50,], A = A[1:50])

score_calc_deriv2(integrand = logit_integrand,
                 parameters = parameters2,
                 propensity_X = X[1:50,], A = A[1:50])
```
```{r}
grad_args <- list()
weight_args <- append(append(integrand_args, integrate_args),
                      list(integrand   = propensity_integrand,
                           allocations = allocations,
                           propensity_X = propensity_X, A = A, G = G, P = P,
                           parameters = parameters0,
                           runSilent  = TRUE, #BB 2015-06-23
                           integrate_allocation = FALSE
                      ))
weightd <- do.call(wght_deriv_array_second, args = append(weight_args, grad_args))
weights <- do.call(wght_matrix_second, args = weight_args)

objs = ipw_point_estimates_mixed_test4(H = H, G = G, A = A, weights = weights, X = cond_X, x0 = x0, neighinfo = NULL, x1= NULL, X_type = c("C", "N"), Con_type = "group")
```

