---
title: "tmp-propensity"
author: "Yihan Bao yb254"
date: "4/6/2023"
output: html_document
---

```{r}
setwd("~/OutSpillover")
dat <- rbind(readRDS("cluster_results/second_propensity_outcome_group1_new_weight.RDS"))
# cluster_results/second_propensity_outcome_neigh.RDS
# cluster_results/second_propensity_neigh (new UVU, diffX)4.RDS
# cluster_results/second_propensity_group1 (new UVU, noc = 100, nsim = 100).RDS
```

```{r}
hq <- quantile(dat$estimate, 0.975)
lq <- quantile(dat$estimate, 0.025)
hq_std <- quantile(dat$std.error, 0.975, na.rm = TRUE)
lq_std <- quantile(dat$std.error, 0.025, na.rm = TRUE)

#dat <- dat[dat$estimate > lq & dat$estimate < hq & dat$std.error > lq_std & dat$std.error < hq_std, ] 

sd(dat$estimate[intersect(which(dat$estimate > lq), which(dat$estimate < hq))])
mean(dat[intersect(which(dat$std.error > lq_std), which(dat$std.error < hq_std)),]$std.error)
sd(dat$estimate)
mean(dat$std.error, na.rm = TRUE)
mean(dat$estimate)
```
5 + 7 + 9 * 0.1 = 12.9
5 + 7 * 0.5 + 9 * 0.5 = 13

```{r}
setwd("~/OutSpillover")

source("utils/weight_matrix.R")
source("utils/integrand.R")
source("utils/utils.R")
source("utils/mixed_effects.R")

source("point_estimates/point_estimates.R")
source("variances/bootstrap_variance.R")
source("variances/regression_variance.R")
source("variances/regression_utils.R")
source("variances/regression_utils_neigh.R")

source("propensity/propensity.R")
source("propensity/point_estimate_propensity.R")
source("propensity/propensity_utils.R")
source("propensity/propensity_effect_calc.R")
source("point_estimates/point_estimates_utils.R")
source("propensity/second_stage_utils.R")

source("propensity/propensity_weighted_regression.R")

library(igraph)
library(lme4)
library(boot)
```

```{r}
graph = make_empty_graph(n = 0, directed = FALSE)
  noc = 10
  ss = 20
  
  repeat{
    g2 = sample_gnp(ss, 0.5, directed = FALSE, loops = FALSE)
    graph = disjoint_union(graph, g2)
    if (clusters(graph)$no == noc){
      break}
  }
  G = rep(1:noc, each = ss)
  
  numerator_alpha = 0.5
  denominator_alphas = c(0.4,0.6)
  P = c(0.5,0.5) 
  # Assume random effect ~ N(0, 0.2^2) for each group
  ranef <- rnorm(noc, mean = 0, sd = 0.2)
  group_ef<- rep(ranef, each = ss)
  
  # assign to group 1 (0.4) and group 2 (0.6) randomly
  G1 = sample(c(1,2), length(unique(G)), replace = TRUE, prob = P)
  G1_alpha = denominator_alphas[G1]
  P1 = sapply(G, function(x) G1_alpha[x])
  
  # for each group with assigned treatment probability, the probability of treatment 
  P2 = rep(NA, length(P1))
  A = rep(NA, length(P1))
  # Assume there are 2 covariates
  X1 <- sample(c("M", "F"), size = length(A), replace = TRUE) # M is 1, F is 0
  X1_num <- ifelse(X1 == "M", 1, 0)
  X2 <- rnorm(length(A), mean = 0.5, sd = 1)
  X <- cbind(X1, X2)
  X_type <- c("C", "N")
  
  # A ～ X1 + X2 + P_2[i] + intercept
  
  
  for (i in 1:length(P1)) {
    # Base denominator assigned to each group
    if(P1[i] == 0.4){
      # mean of X1_num, X2, group_ef = .5, .5, 0
      # intercept = logit(0.4) - 1
      P2[i] = inv.logit(X1_num[i] + X2[i] + group_ef[i] - 1.4 - max(ranef[G1 == 1]))
    }else{
      P2[i] = inv.logit(X1_num[i] + X2[i] + group_ef[i] - 0.6 - max(ranef[G1 == 2]))
    }
  }
  
  df <- as.data.frame((cbind(G, P2)))
  
  for (i in 1:dim(df)[1]) {
    df$A[i] <- sample(c(1, 0), size = 1, prob = c(P2[i], 1-P2[i]))
  }
  A <- df$A
  
  x0 <- as.matrix(c("M", 0.1))
  x1 <- x0
  x1_num <- c(0.1)
  
  X_num <- apply(as.matrix(X[, X_type == "N"]), 2, as.numeric)
  X_cat <- as.matrix(X[, X_type == "C"])
  
  df$treated_neigh <- h_neighsum(graph, df$A, 1) 
  df$interaction1 <- ifelse(X_cat[,1] == "M", 1, 0)  * df$treated_neigh
  df$interaction2 <- X_num[,1] * df$treated_neigh
  
  ##########
  # 2. Outcome model
  aa = 2; bb = 5; cc = 7; dd = 9
  Y = apply(cbind(df$A, df$treated_neigh, df$interaction1, df$interaction2), 1, function(x)  rnorm(1, mean = aa*x[1] + bb*x[2] + cc*x[3] + dd*x[4], sd = 1))  
  H = h_neighborhood(graph, Y, 1) 
  H_M =  h_neighborhood(graph, Y, 1, X_cat, c("M")) 
  df$Y = Y
  df$H = H
  df$H_M = H_M
  
  # 2.1 neighinfo
  neighX = h_neighcov(graph, 1, X, X_type, x1) # average of X for unit j's 1-order neighbor
  neighinfo = list(neighX)
  names(neighinfo) <- c('neighX')
  
  df$X1_num <- X1_num
  df$X2 <- X2
  formula <- H | A  ~  X1_num + X2 + (1|G) | G
  df1 <- df[P1 == 0.4,]
  df2 <- df[P1 == 0.6,]
  
  X <- cbind(1, X1_num, X2)
  allocations = list(c(numerator_alpha, denominator_alphas))
  first_assignments = G1 - 1
  
  cond_X <- cbind(X1, X2)
```

```{r}
parameters1 <- unlist(propensity_parameter(formula, df1)[1])
parameters2 <- unlist(propensity_parameter(formula, df2)[1])
parameters = c(parameters1, parameters2)

# parameters = unlist(propensity_parameter(formula, df)[1])
# parameters = c(parameters, parameters)
P = c(0.5,0.5)
propensity_X = X
ipw_propensity_variance_second(parameters = parameters,
                                   allocations = allocations,
                                   causal_estimation_options = 
                                     list(variance_estimation = 'robust'),
                                   integrate_allocation = FALSE,
                                   H = H, propensity_X = X, P = P,
                                   A = A, G = G, first_assignments = first_assignments,
                                   effect_type = "contrast")

integrand_args <- list()
integrate_args <- list()
propensity_integrand <- logit_integrand_second
grad_args <- list()

weight_args <-list(integrand = propensity_integrand,
                           allocations = allocations,
                           propensity_X = propensity_X, A = A, G = G, P = P,
                           parameters = parameters,
                           runSilent  = TRUE, #BB 2015-06-23
                           integrate_allocation = FALSE)
weightd <- do.call(wght_deriv_array_second, args = append(weight_args, grad_args))
weights <- do.call(wght_matrix_second, args = weight_args)

wght_matrix_second(integrand = propensity_integrand, 
                        allocations = allocations, 
                        G = G, A = A, P = 1,
                        propensity_X = X, 
                        parameters = parameters)

wght_deriv_array_second(parameters = parameters, integrand = propensity_integrand, 
                        allocations = allocations, 
                        G = G, A = A, P = 1,
                        propensity_X = X,
                        integrate_allocation = FALSE)

score_matrix_second(integrand = propensity_integrand,
                         propensity_X = X, A = A, G = G, P = P,
                         parameters = parameters,
                         first_assignments = first_assignments)

```

```{r}
logit_integrand_second_new <- function(b, propensity_X, A, 
                                   parameters,
                                   first_assignment, 
                                   allocation = A, 
                                   randomization = 1)
{
  ## In the case of an intercept-only model, X needs to be converted to matrix
  # for the warning to work
  if(!is.matrix(propensity_X)){
    propensity_X <- as.matrix(propensity_X)
  }
  
  p <- ncol(propensity_X)
  pp <- length(parameters)/(p+1)
  theta <- parameters[((p+1)*(first_assignment)+1):((p+1)*(first_assignment+1))] 
  ## Warnings ##
  # if(p != ncol(X)){
  #   stop('The number of fixed effect parameters is not equal to the number \n
  #        of columns in the covariate matrix')
  # }
  
  if(length(A) != nrow(propensity_X)){
    stop('Length of treatment vector is not equal to number of observations in
         propensity_X matrix')
  }
  
  # Check whether to ignore random effect
  ignore_re <- (length(theta) == p || theta[p + 1] <= 0)
  
  ## Calculations ## 
  if(ignore_re){
    pr.b <- randomization * (stats::plogis(propensity_X %*% theta[1:p]))
  } else {
    if (nrow(X)==1) {
      linpred_vec <- drop(outer(propensity_X %*% theta[1:p], b, '+'))
      ##drop() will return a vector if X has one row - BGB 2017-02-12
      ##solution: create a matrix of one row from that vector - BGB 2017-02-12
      linpred_mat <- matrix(linpred_vec, byrow=TRUE,
                            nrow=1, ncol = length(linpred_vec))
      pr.b <- randomization * (stats::plogis(linpred_mat))
      ##pr.b should not throw errors in the apply() fun below. - BGB 2017-02-12
    } else {
      pr.b <- randomization * (stats::plogis(drop(outer(propensity_X %*% theta[1:p], b, '+'))))
    }
  }
  
  hh <- as.matrix((pr.b/allocation)^A * ((1-pr.b)/(1 - allocation))^(1-A))
  
  if(ignore_re){
    # in this way dnorm integrates to one when integrating from -Inf to Inf
    out <- exp(sum(log(hh))) * stats::dnorm(b, mean=0, sd = 1) 
  } else {
    hha <- apply(hh, 2, function(x) exp(sum(log(x))))
    out <- hha * stats::dnorm(b, mean=0, sd = theta[p + 1])
  }
  #print(b)
  return(out)
}

```

```{r}
setwd("~/OutSpillover")
source("propensity/second_stage_utils.R")

# score_matrix_second(integrand = logit_integrand_second,
#                          propensity_X = X, A = A, G = G, P = P,
#                          parameters = parameters,
#                          first_assignments = first_assignments)

score_matrix_deriv(integrand = logit_integrand_second_old,
                   propensity_X = X, A = A, G = G, P = P,
                   parameters = parameters, first_assignments = first_assignments)


```

```{r}
setwd("~/OutSpillover")
source("propensity/score_utils.R")

score_matrix_deriv_new(integrand = logit_integrand_second_new,
                   propensity_X = X, A = A, G = G, P = P,
                   parameters = parameters, first_assignments = first_assignments)

```

```{r}
ipw_interference_second(propensity_integrand = propensity_integrand,
                        loglihood_integrand = propensity_integrand,
                        allocations = allocations,
                        H = H, propensity_X, A = A, B = A, G = G, P = 1,
                        parameters = parameters[1:4],
                        first_assignments = rep(0, noc), 
                        variance_estimation = "robust",
                        runSilent   = TRUE, 
                        integrate_allocation = FALSE)$point_estimates$outcomes$overall
```

```{r}
ipw_point_estimates_mixed_test4(H = H, G = G, A = A, weights = weights, X = NULL, x0 = NULL, 
                                            neighinfo = NULL, x1= NULL, X_type = NULL,
                                            Con_type = "No-con")$outcomes$overall
```

----
```{r}
parameters = unlist(propensity_parameter(formula, df)[1])

ipw_propensity_variance(parameters = parameters,
                        allocations = allocations,
                        causal_estimation_options = 
                          list(variance_estimation = 'robust'),
                        integrate_allocation = FALSE,
                        H = H, X = X, #as.matrix(cbind(1, X1_num, X2))
                        A = A, G = G, effect_type = "contrast")

ipw_point_estimates_propensity(H = H, G = G, A = A, weights = weights, X = NULL, x0 = NULL, 
                                            neighinfo = NULL, x1= NULL, X_type = NULL,
                                            Con_type = "No-con")$outcomes$overall

wght_matrix(parameters = parameters, integrand = logit_integrand, 
            G = G, A = df$A, P = P, X = cbind(1, X1_num, X2), allocations = allocations)

inferference::interference(formula, allocations = c(0.5, 0.5),
data = df, propensity_integrand = "logit_integrand", causal_estimation_options = 
                          list(variance_estimation = 'robust'))

inferference::wght_deriv_array(parameters = parameters, integrand = logit_integrand, G = G, A = df$A, X = as.matrix(cbind(1, as.numeric(X1_num), as.numeric(X2))), allocations =  c(0.5, 0.5))

inferference::wght_matrix(logit_integrand, allocations =  c(0.5, 0.5), A = df$A, X = as.matrix(cbind(1,as.numeric(X1_num), as.numeric(X2))), G = G, parameters = parameters)

inferference::score_matrix(logit_integrand, X = as.matrix(cbind(1,as.numeric(X1_num), as.numeric(X2))), A = A, G = G, parameters = parameters)
```
```{r}
ipw_propensity_variance_regression(parameters = parameters,
                                   allocations = allocations,
                                   causal_estimation_options = 
                                     list(variance_estimation = 'robust'),
                                   integrate_allocation = FALSE,
                                   propensity_X = X,
                                   H = H, P = P,
                                   A = A, G = G, 
                                   first_assignments = first_assignments,
                                   effect_type = "contrast", 
                                   X = cond_X,
                                   x0 = x0, 
                                   X_type = c("C", "N"),
                                   Con_type = "group")

ipw_point_estimates_mixed_test4(H = H, G = G, A = A, weights = weights, X = cond_X, x0 = x0, 
                                            neighinfo = NULL, x1= NULL, X_type = c("C", "N"),
                                            Con_type = "group")$outcomes$overall
```
10.52361	5.37363	

```{r}
obj_G1 <- ipw_propensity_variance_regression(parameters = parameters,
                                            allocations = allocations,
                                            causal_estimation_options =
                                              list(variance_estimation = 'robust'),
                                            integrate_allocation = FALSE,
                                            propensity_X = X,
                                            H = H, P = P,
                                            A = A, G = G,
                                            first_assignments = first_assignments,
                                            effect_type = "contrast",
                                            X = cbind(X2),
                                            x0 = as.matrix(c(0.1)),
                                            X_type = c("N"),
                                            Con_type = "group")
   
```

```{r}
ipw_point_estimates_mixed_test4(H = H_M, G = G, A = A, weights = weights, X = NULL, x0 = NULL, 
                                neighinfo = neighinfo, x1= as.matrix(x1_num), X_type = c("N"),
                                Con_type = "neigh")$outcomes$overall

ipw_propensity_variance_regression(parameters = parameters,
                                            allocations = allocations,
                                            causal_estimation_options =
                                              list(variance_estimation = 'robust'),
                                            integrate_allocation = FALSE,
                                            H = H_M, propensity_X = X, P = P,
                                            A = A, G = G,
                                            first_assignments = first_assignments,
                                            effect_type = "contrast",
                                            neighinfo = neighinfo,
                                            x1 = as.matrix(x1_num), # x1
                                            X_type = c("N"), # X_type
                                            Con_type = "neigh")
```
0.825844	42.05745	



----
```{r}
propensity_X = X
weight_args <- append(append(integrand_args, integrate_args),
                        list(integrand   = propensity_integrand, 
                             allocations = allocations, 
                             propensity_X = propensity_X, A = A, G = G, P = P,
                             parameters = parameters,
                             runSilent  = runSilent, #BB 2015-06-23
                             integrate_allocation = integrate_allocation
                        ))
weights <- do.call(wght_matrix_second, args = weight_args)

ipw_point_estimates_mixed_test4(H = H, G = G, A = A, weights = weights, X = cond_X, x0 = x0, 
                                            neighinfo = NULL, x1= NULL, X_type =  c("C", "N"),
                                            Con_type = "group")$outcomes$overall
```
```{r}
ipw_point_estimates_propensity_Vmatrix(H, G, A, weights, objs, X = cond_X, x0 = x0, 
                                       neighinfo = NULL, x1= NULL, X_type = c("C", "N"),
                                       Con_type = "group")
```



```{r}
objs = ipw_point_estimates_mixed_test4(H = H, G = G, A = A, weights = weights, X = cond_X, x0 = x0, neighinfo = NULL, x1= NULL, X_type = c("C", "N"), Con_type = "group")

beta_est_eqs <- ipw_point_estimates_propensity_Vmatrix(H = H, G = G, A = A, weights = weights, objs = objs, X = cond_X, x0 = x0, neighinfo = NULL, x1= NULL, X_type = c("C", "N"), Con_type = "group")

colMeans(beta_est_eqs[, , a1, t1,]) 
```

