---
title: "Untitled"
output: html_document
date: "2023-09-26"
---
######
# generating dataset
```{r}
setwd("~/Desktop/OutSpillover")

source("utils/weight_matrix.R")
source("utils/integrand.R")
source("utils/utils.R")
source("utils/mixed_effects.R")

source("point_estimates/point_estimates.R")
source("variances/bootstrap_variance.R")
source("variances/regression_variance.R")
source("variances/regression_utils.R")
source("variances/regression_utils_neigh.R")

source("propensity/propensity.R")
source("propensity/point_estimate_propensity.R")
source("propensity/propensity_utils.R")
source("propensity/propensity_effect_calc.R")
source("point_estimates/point_estimates_utils.R")
source("propensity/second_stage_utils.R")

source("propensity/propensity_weighted_regression.R")

library(igraph)
library(lme4)
library(boot)
```

```{r}
graph = make_empty_graph(n = 0, directed = FALSE)
  noc = 200
  ss = 200
  
  repeat{
    g2 = sample_gnp(ss, 0.5, directed = FALSE, loops = FALSE)
    graph = disjoint_union(graph, g2)
    if (clusters(graph)$no == noc){
      break}
  }
  G = rep(1:noc, each = ss)
  
  numerator_alpha = 0.5
  denominator_alphas = c(0.4,0.6)
  P = c(0.5, 0.5) 
  # Assume random effect ~ N(0, 0.2^2) for each group
  ranef <- rnorm(noc, mean = 0, sd = 0.2)
  group_ef<- rep(ranef, each = ss)
  
  # assign to group 1 (0.4) and group 2 (0.6) randomly
  G1 = sample(c(1,2), length(unique(G)), replace = TRUE, prob = P)
  G1_alpha = denominator_alphas[G1]
  P1 = sapply(G, function(x) G1_alpha[x])
  
  # for each group with assigned treatment probability, the probability of treatment 
  P2 = rep(NA, length(P1))
  A = rep(NA, length(P1))
  # Assume there are 2 covariates
  X1 <- sample(c("M", "F"), size = length(A), replace = TRUE) # M is 1, F is 0
  X1_num <- ifelse(X1 == "M", 1, 0)
  X2 <- rnorm(length(A), mean = 0.5, sd = 0.5)
  X <- cbind(X1, X2)
  X_type <- c("C", "N")
  
  # A ～ X1 + X2 + P_2[i] + intercept
  
  
  for (i in 1:length(P1)) {
    # Base denominator assigned to each group
    if(P1[i] == 0.4){
      # mean of X1_num, X2, group_ef = .5, .5, 0
      # intercept = logit(0.4) - 1
      #P2[i] = inv.logit(X1_num[i] + X2[i] + group_ef[i] - 1.4) #- max(ranef[G1 == 1])
      P2[i] = sample(c(1,0), 1, prob = c(0.4, 0.6))
    }else{
      P2[i] = sample(c(1,0), 1, prob = c(0.6, 0.4))
      #inv.logit(X1_num[i] + X2[i] + group_ef[i] - 0.6)#- max(ranef[G1 == 2]
    }
  }
  
  df <- as.data.frame((cbind(G, P2)))
  
  for (i in 1:dim(df)[1]) {
    df$A[i] <- sample(c(1, 0), size = 1, prob = c(P2[i], 1-P2[i]))
  }
  A <- df$A
  
  x0 <- as.matrix(c("M", 0.1))
  x1 <- x0
  x1_num <- c(0.1)
  
  X_num <- apply(as.matrix(X[, X_type == "N"]), 2, as.numeric)
  X_cat <- as.matrix(X[, X_type == "C"])
  
  df$treated_neigh <- h_neighsum(graph, df$A, 1) 
  # df$interaction1 <- ifelse(X_cat[,1] == "M", 1, 0)  * df$treated_neigh
  # df$interaction2 <- X_num[,1] * df$treated_neigh
  df$interaction1 <- cov_neighsum(graph, A, 1, X = ifelse(X_cat[,1] == "M", 1, 0))
  df$interaction2 <- cov_neighsum(graph, A, 1, X = X_num[,1])
  
  ##########
  # 2. Outcome model
  aa = 0; bb = 0; cc = 0; dd = 10
  Y = apply(cbind(df$A, df$treated_neigh, df$interaction1, df$interaction2), 1, 
            function(x)  rnorm(1, mean = aa*x[1] + bb*x[2] + cc*x[3] + dd*x[4], sd = 1))  
  H = h_neighborhood(graph, Y, 1) 
  H_M =  h_neighborhood(graph, Y, 1, X_cat, c("M")) 
  df$Y = Y
  df$H = H
  df$H_M = H_M
  
  # 2.1 neighinfo
  neighX = h_neighcov(graph, 1, X, X_type, x1) # average of X for unit j's 1-order neighbor
  neighinfo = list(neighX)
  names(neighinfo) <- c('neighX')
  
  df$X1_num <- X1_num
  df$X2 <- X2
  formula <- H | A  ~  X1_num + X2 + (1|G) | G
  df1 <- df[P1 == 0.4,]
  df2 <- df[P1 == 0.6,]
  
  X <- cbind(1, X1_num, X2)
  allocations = list(c(numerator_alpha, denominator_alphas))
  first_assignments = G1 - 1
  
  cond_X <- cbind(X1, X2)
```

######
# two-stage with parameter1 = parameter2
```{r}
# parameters1 <- unlist(propensity_parameter(formula, df1)[1])
# parameters2 <- unlist(propensity_parameter(formula, df2)[1])
# parameters = c(parameters1, parameters2)

parameters = unlist(propensity_parameter(formula, df)[1])
parameters = c(parameters, parameters)
P = c(0.3,0.7)
propensity_X = X
ipw_propensity_variance_second(parameters = parameters,
                                   allocations = allocations,
                                   causal_estimation_options = 
                                     list(variance_estimation = 'robust'),
                                   integrate_allocation = FALSE,
                                   H = H, propensity_X = X, P = P,
                                   A = A, G = G, first_assignments = first_assignments,
                                   effect_type = "contrast")

integrand_args <- list()
integrate_args <- list()
propensity_integrand <- logit_integrand_second
grad_args <- list()

weight_args <-list(integrand = propensity_integrand,
                           allocations = allocations,
                           propensity_X = propensity_X, A = A, G = G, P = P,
                           parameters = parameters,
                           runSilent  = TRUE, #BB 2015-06-23
                           integrate_allocation = FALSE)
weightd <- do.call(wght_deriv_array_second, args = append(weight_args, grad_args))
weights <- do.call(wght_matrix_second, args = weight_args)

# wght_matrix_second(integrand = propensity_integrand, 
#                         allocations = allocations, 
#                         G = G, A = A, P = 1,
#                         propensity_X = X, 
#                         parameters = parameters)
# 
# wght_deriv_array_second(parameters = parameters, integrand = propensity_integrand, 
#                         allocations = allocations, 
#                         G = G, A = A, P = 1,
#                         propensity_X = X,
#                         integrate_allocation = FALSE)
# 
score_matrix_second(integrand = logit_integrand_second,
                         propensity_X = X, A = A, G = G, P = P,
                         parameters = parameters,
                         first_assignments = first_assignments)

```

#######
# one stage
```{r}
parameters = unlist(propensity_parameter(formula, df)[1])

ipw_propensity_variance(parameters = parameters,
                        allocations = allocations,
                        causal_estimation_options = 
                          list(variance_estimation = 'robust'),
                        integrate_allocation = FALSE,
                        H = H, X = X,
                        A = A, G = G, effect_type = "contrast")

inferference::interference(formula, allocations = c(0.5, 0.5),
data = df, propensity_integrand = "logit_integrand", causal_estimation_options = 
                          list(variance_estimation = 'robust'))

inferference::wght_deriv_array(parameters = parameters, integrand = logit_integrand, G = G, A = df$A, X = as.matrix(cbind(1, as.numeric(X1_num), as.numeric(X2))), allocations =  c(0.5, 0.5))

```

```{r}
inferference::score_matrix(logit_integrand, X = as.matrix(cbind(1,as.numeric(X1_num), as.numeric(X2))), 
                           A = A, G = G, parameters = parameters[1:4])
```

######
# understand how point estimate works
```{r}
parameters1 <- unlist(propensity_parameter(formula, df1)[1])
parameters2 <- unlist(propensity_parameter(formula, df2)[1])
parameters = c(parameters1, parameters2)

obj_G1 <- ipw_propensity_variance_regression(parameters = parameters,
                                                allocations = allocations,
                                                causal_estimation_options = 
                                                  list(variance_estimation = 'robust'),
                                                integrate_allocation = FALSE,
                                                propensity_X = X,
                                                H = H, P = P,
                                                A = A, G = G, 
                                                first_assignments = first_assignments,
                                                effect_type = "outcome", 
                                                X = cbind(X2),
                                                x0 = as.matrix(c(0.1)),
                                                X_type = c("N"),
                                                Con_type = "group")
 
```
122.8643	3.291218	116.4136	129.315	
106.4095	3.169949	100.1965	112.6225	

```{r}
parameters1 <- unlist(propensity_parameter(formula, df1)[1])
parameters2 <- unlist(propensity_parameter(formula, df2)[1])
parameters = c(parameters1, parameters2)#rep(0, 4)

propensity_X = cbind(1, X1_num, X2)
weight_args <-list(integrand = logit_integrand_second,
                           allocations = allocations,
                           propensity_X = propensity_X, A = A, G = G, P = P,
                           parameters = parameters,
                           runSilent  = TRUE, #BB 2015-06-23
                           integrate_allocation = FALSE)
weights <- do.call(wght_matrix_second, args = weight_args)

```

 
```{r}

p = 1; k = 1; N = length(dimnames(weights)[[1]])
numerator_alphas <- 0.5
a = 1
 
weights <- array(c(weights, 1), dim=c(N, 1, k))
weights_trt <- array(dim= c(length(A), p, k))
    
for(pp in 1:p){
  for (kk in 1:k) {
    weights_trt[ , pp, kk] <- apply(as.array(G), 1, function(x) weights[,pp,kk][x])
    weights_trt[ , pp, kk] <- weights_trt[ , pp, kk] * (A == a)/
      (numerator_alphas[kk]^a * (1-numerator_alphas[kk])^(1-a)) # add some comments
  }
}
```
 
```{r}
weights_df <- weights_trt[, , 1]

# test for numerical only case first
X <- cbind(X2)
X_type = c("N")
x0 = as.matrix(c(0.1))

X_cat <- as.matrix(X[, X_type == "C"])
X_num <- apply(as.matrix(X[, X_type == "N"]), 2, as.numeric)
num_names <- colnames(X)[X_type == "N"]
x0_cat <- x0[X_type == "C"]
x0_num <- as.numeric(x0[X_type == "N"])
trt_cond <- which(A == a)

if (sum(X_type == "C") > 0){
  ind_cond <- which(apply(X_cat, 1, function(x) prod(x == x0_cat)) == 1)
}else{
  ind_cond <- 1:dim(X_cat)[1]}

if (sum(X_type == "N") > 0){
  group_df <- as.data.frame(cbind(weights_df, H, G, X_num))
  colnames(group_df) <- c('w', 'H', 'G', num_names)
  group_df$weighted_H <- group_df$w * group_df$H
  fits_df <- group_df[intersect(ind_cond,trt_cond), ]
  fits <- lmList(as.formula(paste("weighted_H ~ ", paste(num_names, 
                                                         collapse= "+ "), "| G")), data = fits_df)
  cond_coef <- as.matrix(coef(fits))
  overall_fits <- lm(as.formula(paste("H ~ ", paste(num_names, collapse= "+ "))),
                     weights = w, data=fits_df)
  overall_coef <- as.vector(coef(overall_fits))}

overall_coef  
```
c = 1, d = 10:
a = 0
112.667166   2.272652
100.632362   2.534417
97.926811  1.903289 (w cond)
a = 1
122.336012   5.282822
105.901749   5.077431
106.934651   3.781007 (w cond) 


c = 0, d = 10:

a = 0
100.2077757   0.4296678
98.9347252 -0.8873461

a = 1
98.725656  8.411993
95.356012  9.110754 (w cond)